package com.zhongjh.app.data.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhongjh.app.entity.db.SearchContent;

import com.zhongjh.app.data.db.dao.SearchContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchContentDaoConfig;

    private final SearchContentDao searchContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchContentDaoConfig = daoConfigMap.get(SearchContentDao.class).clone();
        searchContentDaoConfig.initIdentityScope(type);

        searchContentDao = new SearchContentDao(searchContentDaoConfig, this);

        registerDao(SearchContent.class, searchContentDao);
    }
    
    public void clear() {
        searchContentDaoConfig.clearIdentityScope();
    }

    public SearchContentDao getSearchContentDao() {
        return searchContentDao;
    }

}
